# ==================================== 全局设置 ====================================

## 顶部预览大图
banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/banner.jpg

## Hexo的网页图标
favicon: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/favicon.png

## 是否强制全局HTTPS
force_https: true

## 自定义JS
custom_js:
  ### 鼠标点击出小爱心❤
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/js/love.js
  ### 鼠标跟随小星星
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/js/xiaoxingxing.js
  ### 动态彩带
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/js/caidai.js
  ### 自定义JavaScript
  - /js/custom.js
  ### AI助手JavaScript
  - /js/ai-assistant.js

## 自定义CSS
custom_css: 
  ### 引入 iconfont 的图标（这是我的iconfont项目链接，最好可以换成你自己的）
  - //at.alicdn.com/t/c/font_3846514_kabxni94auf.css
  ### 鼠标指针美化
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/css/shubiao.css
  ### 滚动条美化
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/css/gundongtiao.css
  ### 自定义样式
  - /css/custom.css
  ### AI助手样式
  - /css/ai-assistant.css

## 暗黑模式设置
dark_mode:
  enable: true
  default: auto
  button: true

## 导航栏设置
navbar:
  ### 博客标题
  blog_title: Wake 的博客
  ### 导航菜单
  menu:
    - { key: '首页', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: '归档', link: '/archives', icon: 'iconfont icon-books' }
    - { key: '分类', link: '/categories', icon: 'iconfont icon-th-large'}
    - { key: '标签', link: '/tags/', icon: 'iconfont icon-tags-fill'}
    - { key: '关于', link: '/about/', icon: 'iconfont icon-user-fill'}
    - { key: '友链', link: '/links/', icon: 'iconfont icon-link-fill' }
    - {
      key: '文档',
      icon: 'iconfont icon-book',
      submenu: [
        { key: '主题博客', link: 'https://hexo.fluid-dev.com/' },
        { key: '配置指南', link: 'https://hexo.fluid-dev.com/docs/guide/' },
        { key: '图标用法', link: 'https://hexo.fluid-dev.com/docs/icon/' }
      ]
    }
  ### 导航栏毛玻璃效果，2.0新增
  ground_glass:
    enable: true
    # 模糊程度
    blur: 10px

## 关于页设置
about:
  ## 关于页的顶部预览图
  banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/about.jpg
  ### 你的头像
  avatar: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/avatar.jpg
  ### 你的昵称
  name: "Wake"
  ### 个人简介
  intro: "一起学习，一起进步"
  ### 外链设置
  icons:
    - { class: 'iconfont icon-github-fill', link: '你的链接', tip: 'GitHub' }
    - { class: 'iconfont icon-gitee-fill-round', link: '你的链接', tip: 'Gitee' }
    - { class: 'iconfont icon-csdn', link: '你的链接', tip: 'CSDN' }
    - { class: 'iconfont icon-qq', qrcode: '你的链接' }
    - { class: 'iconfont icon-weixin', qrcode: '你的链接' }
  ## 关于页文章内容
  content:
    enable: true
    # 自定义文章
    custom: |
      <div style="text-align:center">
        <div>
          <img src="https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/avatar.jpg" style="width:120px;border-radius:50%;margin-bottom:15px" />
        </div>
        <div>
          <p style="font-size:1.5rem;font-weight:bold;margin-bottom:5px">Wake</p>
          <p style="color:#999;margin-top:0">技术爱好者，终身学习者</p>
        </div>
        <div>
          <p style="margin:15px 0">欢迎来到我的博客！我会在这里分享技术知识、学习心得和生活感悟。</p>
          <p>座右铭：一起学习，一起进步！</p>
        </div>
      </div>

## 友情链接页设置
links:
  ### 友情链接页的顶部预览图
  banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/links.jpg
  items:
    - {
      title: 'Wake',
      intro: 'Wake 的 CSDN',
      link: 'https://www.csdn.net/',
      avatar: 'https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/csdn.png'
    }
    - {
      title: 'Fluid Docs',
      intro: 'Fluid 主题使用指南',
      link: 'https://hexo.fluid-dev.com/docs/',
      avatar: '/img/favicon.png'
    }
  ### 默认头像
  default_avatar: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/default_avatar.png

## 标签页设置
tag:
  ### 标签页的顶部预览图
  banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/tags.jpg
  
## 分类页设置
category:
  ### 分类页的顶部预览图
  banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/categories.jpg
  
## 归档页设置
archive:
  ### 归档页的顶部预览图
  banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/archives.jpg

## 懒加载设置
lazyload:
  ### 是否启用懒加载
  enable: true
  ### 指定加载时的占位图片
  loading_img: /img/loading.gif
  ### 为 true 时，懒加载仅在文章页生效，如果自定义页面需要使用，可以在 Front-matter (opens new window)里指定
  onlypost: false
  ### 触发加载的偏移倍数，基数是视窗高度（即提前 N 屏高度触发加载），可根据部署环境的请求速度调节
  offset_factor: 2
 
## 全局字体设置
font:  
  ### 全局字号
  font_size: 16px
  ### 全局字体族
  font_family: "Microsoft YaHei"
  ### 代码字号
  code_font_size: 85%
  
# ==================================== 首页设置 ====================================
index:
  ## 首页顶部大图
  banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/index.jpg
  ## 打字机设置
  slogan:
    ### 是否启用打字机
    enable: true
    ### 打字机文字内容
    text: 一起学习，一起进步
    ### 打字机水平位置 left right center
    text_align: center
  ## 自动摘要
  auto_excerpt:
    enable: true
    # 摘要长度
    length: 150
  ## 文章跳转方式 _blank：新标签页打开  _self：当前标签页打开
  post_url_target: _blank
  ## 文章信息设置：可配置隐藏包括发布时间、分类、标签
  post_meta:
    date: true
    category: true
    tag: true
  # 首页副标题的独立设置
  subtitle:
    enable: true
    # 打字机效果 若开启打字机，则开启
    typing: true
    # 打字机时延
    typing_speed: 100
    # 循环播放
    loop: true
    # 如果不想使用打字机效果，可以使用静态文字
    text: "分享技术，记录生活"
  # 添加特色卡片区域
  features:
    enable: true
    # 卡片数据
    data:
      - name: 最新文章
        icon: iconfont icon-books
        text: 查看最新发布的技术博客
        link: /archives/
        color: "#49b1f5"
      - name: 我的分类
        icon: iconfont icon-th-large
        text: 浏览文章分类
        link: /categories/
        color: "#ff7242"
      - name: 热门标签
        icon: iconfont icon-tags-fill
        text: 探索热门技术标签
        link: /tags/
        color: "#42c02e"
  # 显示文章分类
  categories:
    enable: true
    title: 热门分类
    icon: iconfont icon-th-large
    limit: 6  # 最多显示分类数量
    mobile_limit: 3  # 移动端显示数量
    color: true  # 使用彩色显示
  
# ==================================== 文章页设置 ====================================
post:
  ## 文章页banner
  banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/post.jpg
  ## 缩略图封面
  # 文章默认封面图
  default_index_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/default.jpg
  # 是否根据文章内容自动生成封面
  auto_cover: true
  # 自动生成封面的设置
  auto_cover_types:
    - 'unsplash'    # https://source.unsplash.com
    - 'picsum'      # https://picsum.photos
    - 'placeholder' # https://placehold.co
  ## 日期/字数/阅读时长/阅读数 设置
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: true
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: " YYYY 年 MM 月 DD 日 , a hh:mm , dddd"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
    views:  # 阅读次数
      enable: true
      source: "busuanzi"  # 统计数据来源，可选：leancloud | busuanzi   
      format: "{} 次"
  ## 文章页脚
  copyright:
    enable: false
    # 展示作者
    author:
      enable: true
    # 展示发布日期
    post_date:
      enable: true
      format: "LL"
    # 展示许可协议
    license:
      enable: true
      # 许可协议地址，支持自定义
      license: "CC BY-NC-SA 4.0"
      link: "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh"
      text: "本文采用 CC BY-NC-SA 4.0 协议，转载请注明出处"
  ## 文章底部上一篇下一篇
  prev_next:
    enable: true
  ## 文章内容目录
  toc:
    enable: true
    # 目录层级
    level: 3
    # 置于边栏
    placement: right
  ## 文章分享功能
  share:
    enable: true
    # 分享服务
    services:
      - 'qq'       # QQ好友
      - 'wechat'   # 微信
      - 'weibo'    # 微博
      - 'email'    # 电子邮件
      - 'facebook' # Facebook
      - 'twitter'  # Twitter
      - 'linkedin' # LinkedIn

## 评论系统设置
comments:
  enable: true
  # 指定的插件，需要同时设置对应插件的必要参数
  # 目前支持 valine | waline | gitalk
  type: gitalk

## 评论插件设置 - Gitalk
gitalk:
  clientID: # GitHub Application Client ID
  clientSecret: # GitHub Application Client Secret
  repo: # GitHub repository
  owner: # GitHub repository owner
  admin: # GitHub repository owner and collaborators who can initialize github issues
  language: zh-CN # en | zh-CN
  labels: gitalk # GitHub issue labels
  perPage: 15 # Pagination size, with maximum 100

## 页面布局
page:
  banner_img: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/page.jpg

# ==================================== 功能配置 ====================================

## 搜索功能
search:
  enable: true
  # 搜索索引文件的路径，可以是相对路径或外站的绝对路径
  path: /local-search.xml
  # 文本框提示语
  label: 搜索
  # 是否在搜索索引文件中添加分类信息
  field: post
  # 搜索栏的宽度，可以设置百分比或像素
  width: 50%
  # 搜索预览的长度，如果值为 -1 则不显示预览
  preview: 50
  # 模糊匹配
  fuzzy: true

## 页面点击效果
fun_features:
  # 为 subtitle 添加打字机效果
  typing:
    enable: true
    # 打印速度，数字越大越慢
    typeSpeed: 70
    # 游标字符
    cursorChar: "_"
    # 是否循环播放效果
    loop: false
  # 为文章内容中的标题添加锚图标
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    # 图标样式 line | minimal
    placement: right
    # 显示延迟毫秒数
    visible: hover
    # 图标大小，单位是 px
    icon: "#"
  # 在首页的文章卡片上显示鼠标悬停效果
  post_card:
    enable: true

## 回到顶部按钮
scroll_top_arrow:
  enable: true
  # 是否在移动端显示
  mobile_enable: true

## 代码块设置
code:
  ## 是否开启复制代码的按钮
  copy_btn: true
  ## 高亮设置
  highlight:
    ### 是否开启代码高亮
    enable: true
    ### 是否开启行号
    line_number: true
    ### 选择生成高亮的库，可选项: highlightjs、prismjs，对应下面两组配置
    lib: "highlightjs"
    highlightjs:
      style: 'atom-one-dark'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true

## 统计功能
web_analytics:  
  enable: true
  # 百度统计的Key
  baidu: 41fc030db57d5570dd22f78997dc4a7e
  # 不蒜子统计
  busuanzi:
    enable: true
    # 不蒜子 API 地址
    script_url: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
    # 自定义统计格式，{} 是数字的占位符（必须包含）
    site_uv: true  # 开启站点访客统计
    site_pv: true  # 开启站点访问量统计
    page_pv: true  # 开启页面访问量统计

## 底部信息
footer:
  # 网站创建时间
  since: 2023
  # ICP备案信息，仅中国大陆网站需要
  icp:
    enable: false
    # 备案号
    no: 
  # 公安备案信息，仅中国大陆网站需要
  beian:
    enable: false
    # 备案号
    no: 
  # 显示感谢 Fluid 主题
  support:
    enable: true
    # 显示主题信息
    href: "https://hexo.fluid-dev.com/"
    # 显示文字
    text: "Fluid"
  # 自定义页脚内容，以 HTML 格式字符串为内容
  custom: 
    enable: true
    content: '
      <div>
        <span id="timeDate">载入天数...</span>
        <span id="times">载入时分秒...</span>
        <script>
          var now = new Date();
          function createtime() {
            var grt = new Date("02/10/2023 00:00:00"); // 此处修改你的建站时间
            now.setTime(now.getTime() + 250);
            days = (now - grt) / 1000 / 60 / 60 / 24;
            dnum = Math.floor(days);
            hours = (now - grt) / 1000 / 60 / 60 - (24 * dnum);
            hnum = Math.floor(hours);
            if (String(hnum).length == 1) {
              hnum = "0" + hnum;
            }
            minutes = (now - grt) / 1000 / 60 - (24 * 60 * dnum) - (60 * hnum);
            mnum = Math.floor(minutes);
            if (String(mnum).length == 1) {
              mnum = "0" + mnum;
            }
            seconds = (now - grt) / 1000 - (24 * 60 * 60 * dnum) - (60 * 60 * hnum) - (60 * mnum);
            snum = Math.round(seconds);
            if (String(snum).length == 1) {
              snum = "0" + snum;
            }
            document.getElementById("timeDate").innerHTML = "本站已安全运行 " + dnum + " 天 ";
            document.getElementById("times").innerHTML = hnum + " 小时 " + mnum + " 分 " + snum + " 秒";
          }
          setInterval("createtime()", 250);
        </script>
      </div>
    '
  ## 统计访问人数设置
  statistics:
    enable: true
    source: "busuanzi"
    pv_format: "总访问量 {} 次"
    uv_format: "总访客数 {} 人"
    # 添加自定义选项，使用当前数据重置统计起点
    start_time: "2023-05-01"  # 统计开始时间

## 网页代码注入，可用于添加统计代码等
inject:
  enable: true
  head:
    - |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/all.min.css">
    - |
      <style>
        /* 自定义滚动条样式 */
        ::-webkit-scrollbar {
          width: 8px;
          height: 8px;
        }
        ::-webkit-scrollbar-track {
          background-color: rgba(73, 177, 245, 0.2);
          border-radius: 4px;
        }
        ::-webkit-scrollbar-thumb {
          background-color: #49b1f5;
          border-radius: 4px;
        }
        /* 文章标题动态下划线 */
        .index-header .post-title::after {
          content: "";
          display: block;
          margin: 5px auto 0;
          width: 0;
          height: 2px;
          background: #49b1f5;
          transition: all 0.4s ease-in-out;
        }
        .index-header:hover .post-title::after {
          width: 100%;
        }
        /* 增强标题样式 */
        h1, h2, h3, h4, h5, h6 {
          border-left: 4px solid #49b1f5;
          padding-left: 10px;
          background-color: rgba(73, 177, 245, 0.1);
          border-radius: 0 3px 3px 0;
        }
      </style>
    - |
      <!-- 添加结构化数据 -->
      <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "WebSite",
          "name": "Wake的博客",
          "url": "https://uwakeme.top",
          "description": "Wake的个人技术博客，专注分享技术知识、学习心得和生活感悟",
          "author": {
            "@type": "Person",
            "name": "Wake"
          },
          "publisher": {
            "@type": "Organization",
            "name": "Wake的博客",
            "logo": {
              "@type": "ImageObject",
              "url": "https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/avatar.jpg"
            }
          }
        }
      </script>
  body_end:
    - |
      <!-- 为文章页添加结构化数据 -->
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          const isPostPage = document.querySelector('.post-content');
          if (isPostPage) {
            const title = document.querySelector('.post-title').innerText;
            const dateElement = document.querySelector('.post-meta .datetime');
            const date = dateElement ? dateElement.getAttribute('content') : '';
            const author = document.querySelector('meta[name="author"]').getAttribute('content') || 'Wake';
            const url = window.location.href;
            const description = document.querySelector('meta[name="description"]').getAttribute('content');
            const image = document.querySelector('.post-content img');
            const imageUrl = image ? image.src : 'https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/default.jpg';
            
            // 创建博客文章结构化数据
            const articleSchema = {
              "@context": "https://schema.org",
              "@type": "BlogPosting",
              "headline": title,
              "image": imageUrl,
              "editor": author,
              "author": {
                "@type": "Person",
                "name": author
              },
              "publisher": {
                "@type": "Organization",
                "name": "Wake的博客",
                "logo": {
                  "@type": "ImageObject",
                  "url": "https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/avatar.jpg"
                }
              },
              "url": url,
              "datePublished": date,
              "dateCreated": date,
              "dateModified": date,
              "description": description,
              "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": url
              }
            };
            
            // 将结构化数据添加到页面
            const scriptElement = document.createElement('script');
            scriptElement.type = 'application/ld+json';
            scriptElement.innerHTML = JSON.stringify(articleSchema);
            document.head.appendChild(scriptElement);
          }
        });
      </script>