# Butterfly主题配置文件
# 官方文档: https://butterfly.js.org/

# 网站设置
nav:
  logo: # 网站logo
  display_title: true
  fixed: false # 导航栏是否固定

# 网站图标
favicon: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/favicon.png

# 菜单设置
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  分类: /categories/ || fas fa-folder-open
  标签: /tags/ || fas fa-tags
  友链: /links/ || fas fa-link
  关于: /about/ || fas fa-heart

# 代码块设置
highlight_theme: light # light | dark | false
highlight_copy: true # 复制按钮
highlight_lang: true # 显示代码语言
highlight_shrink: false # 代码块收缩
highlight_height_limit: false # 代码高度限制

# 代码块复制提示词
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

# 社交图标
social:
  fab fa-github: https://github.com/uwakeme || Github
  fas fa-envelope: mailto:your-email@example.com || Email

# 搜索设置
local_search:
  enable: true
  preload: false
  CDN:

# 数学公式
mathjax:
  enable: false
  per_page: false

katex:
  enable: false
  per_page: false
  hide_scrollbar: true

# 图片设置
# 图片懒加载
lazyload:
  enable: true
  field: site # site/post
  placeholder: # 占位图
  blur: false # 模糊效果

# 图片放大
medium_zoom: false
fancybox: true

# 页面设置
index_img: # 主页顶部图
default_top_img: # 默认顶部图
archive_img: # 归档页顶部图
tag_img: # 标签页顶部图
tag_per_img: # 标签页每个标签的图片
category_img: # 分类页顶部图
category_per_img: # 分类页每个分类的图片

cover:
  # 是否显示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面显示的位置
  # 三个值可配置 left , right , both
  position: both
  # 当没有设置cover时，默认的封面显示
  default_cover:
    # 当配置多张图片时，会随机选择一张作为cover
    # 此处可以使用相对路径和绝对路径
    - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手机页面是否显示侧边栏
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: 一起学习，一起进步
    button:
      enable: true
      icon: fab fa-github
      text: 关注我
      link: https://github.com/uwakeme
  card_announcement:
    enable: true
    content: 欢迎来到我的博客！这里分享技术知识、学习心得和生活感悟。
  card_recent_post:
    enable: true
    limit: 5 # 显示的文章数量
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # 显示的分类数量
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # 显示的标签数量
    color: false
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # 显示的归档数量
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

# 页脚设置
footer:
  owner:
    enable: true
    since: 2024
  custom_text: # 自定义文本
  copyright: true # Copyright of theme and framework

# 主页文章节选
index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

# 锚点
anchor:
  button:
    enable: false
    always_show: false
    icon: # the unicode value of Font Awesome icon, such as '\3423'
  auto_update: false # when you scroll in post, the URL will update according to header id.

# 图片点击放大已在上面配置

# 阅读模式
readmode: true

# 夜间模式
darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically (自动切换 dark mode和 light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: false
  # Set the light mode time. The value is between 0 and 24. If not set, the default value is 6 and 18
  start: # 8
  end: # 22

# 自动生成按钮
auto_open_sidebar:
  enable: true

# 网站验证
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:

# Bing Webmaster tools verification setting
# See: https://www.bing.com/toolbox/webmaster/
bing_site_verification:

# Yandex Webmaster tools verification setting
# See: https://webmaster.yandex.ru/
yandex_site_verification:

# Baidu Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification:

# 360 Webmaster tools verification setting
# see http://zhanzhang.so.com/
qihu_site_verification:

# 分析统计
# Google Analytics
# https://developers.google.com/analytics/devguides/collection/analyticsjs/
google_analytics:

# Baidu Analytics
# https://tongji.baidu.com/web/welcome/login
baidu_analytics:

# Tencent Analytics
# https://mta.qq.com
tencent_analytics:

# CNZZ Analytics
# https://www.umeng.com/
cnzz_analytics:

# Cloudflare Analytics
# https://www.cloudflare.com/web-analytics/
cloudflare_analytics:

# Microsoft Clarity
# https://clarity.microsoft.com/
microsoft_clarity:

# 广告
# Google Adsense (谷歌广告)
google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: # your Google Adsense client id
  enable_page_level_ads: true

# 网站图标已在上面设置

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: false
  manifest: /pwa/manifest.json
  apple_touch_icon: /pwa/apple-touch-icon.png
  favicon_32_32: /pwa/32.png
  favicon_16_16: /pwa/16.png
  mask_icon: /pwa/safari-pinned-tab.svg

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta:
  enable: true
  option:
    # twitter_card:
    # twitter_image:
    # twitter_id:
    # twitter_site:
    # google_plus:
    # fb_admins:
    # fb_app_id:

# 添加CSS和JS
inject:
  head:
    - <link rel="stylesheet" href="//at.alicdn.com/t/c/font_3846514_kabxni94auf.css">
    - <link rel="stylesheet" href="/css/custom.css">
    - <link rel="stylesheet" href="/css/ai-assistant.css">
  bottom:
    - <script src="/js/custom.js"></script>
    - <script src="/js/ai-assistant.js"></script>
    - <script src="https://cdn.jsdelivr.net/npm/mermaid@9.4.0/dist/mermaid.min.js"></script>

# CDN设置
CDN:
  # The CDN provider of internal scripts (主题内部 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( dev版的主题只能设置为 local )
  internal_provider: local

  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # when set it to local, you need to install hexo-butterfly-extjs
  third_party_provider: jsdelivr

  # Add version number to CDN, true or false
  version: false

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
