# Butterfly主题配置文件
# 官方文档: https://butterfly.js.org/

# 网站设置
nav:
  logo: # 网站logo
  display_title: true
  fixed: false # 导航栏是否固定

# 网站图标
favicon: https://cdn.jsdelivr.net/gh/uwakeme/cdn@main/img/favicon.png

# 头像
avatar:
  img: /img/avatar.jpeg
  effect: true # 頭像會一直轉圈

# 主頁subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # Customize typed.js
  # https://github.com/mattboldt/typed.js/#customization
  typed_option:
  # source 調用第三方服務
  # false 關閉調用
  # 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # 2  調用一句網（簡體） http://yijuzhan.com/
  # 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: true
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:

# 菜单设置
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  分类: /categories/ || fas fa-folder-open
  标签: /tags/ || fas fa-tags
  友链: /links/ || fas fa-link
  关于: /about/ || fas fa-heart

# 代码块设置
highlight_theme: light # light | dark | false
highlight_copy: true # 复制按钮
highlight_lang: true # 显示代码语言
highlight_shrink: false # 代码块收缩
highlight_height_limit: false # 代码高度限制

# 代码块复制提示词
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

# 社交图标
social:
  fab fa-github: https://github.com/uwakeme || Github
  fas fa-envelope: mailto:wakemeup2025@126.com || Email

search:
  # Choose: algolia_search / local_search / docsearch
  # leave it empty if you don't need search
  use: local_search
  placeholder: 请输入搜索内容


# 搜索设置
local_search:
  enable: true
  labels:
    input_placeholder: 请输入搜索内容
    hits_empty: "未找到相关内容: ${query}" # 如果没有查到内容相关内容显示

# 数学公式
mathjax:
  enable: false
  per_page: false

katex:
  enable: false
  per_page: false
  hide_scrollbar: true

# 图片设置
# 图片懒加载
lazyload:
  enable: true
  field: site # site/post
  placeholder: /img/loading.gif # 占位图
  blur: 1 # 模糊效果

# 图片放大
medium_zoom: true
fancybox: true

# 页面设置
index_img: /img/index_img.jpg # 主页顶部图
default_top_img: /img/bingdaohuanlu.jpg # 默认顶部图
archive_img: # 归档页顶部图
tag_img: # 标签页顶部图
tag_per_img: # 标签页每个标签的图片
category_img: # 分类页顶部图
category_per_img: # 分类页每个分类的图片

cover:
  # 是否显示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面显示的位置
  # 三个值可配置 left , right , both
  position: both
  # 当没有设置cover时，默认的封面显示
  default_cover:
    # 当配置多张图片时，会随机选择一张作为cover
    # 此处可以使用相对路径和绝对路径
    - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手机页面是否显示侧边栏
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: 一起学习，一起进步
    button:
      enable: true
      icon: fab fa-github
      text: 关注我
      link: https://github.com/uwakeme
  card_announcement:
    enable: true
    content: 欢迎来到我的博客！这里分享技术知识、学习心得和生活感悟。
  card_recent_post:
    enable: true
    limit: 5 # 显示的文章数量
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # 显示的分类数量
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # 显示的标签数量
    color: false
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # 显示的归档数量
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

# 页脚设置
footer:
  owner:
    enable: true
    since: 2024
  custom_text: # 自定义文本
  copyright: true # Copyright of theme and framework

# 主页文章节选
index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

# 锚点
anchor:
  button:
    enable: true
    always_show: false
    icon: # the unicode value of Font Awesome icon, such as '\3423'
  auto_update: true # when you scroll in post, the URL will update according to header id.

# 阅读模式
readmode: true

# 夜间模式
darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically (自动切换 dark mode和 light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: false
  # Set the light mode time. The value is between 0 and 24. If not set, the default value is 6 and 18
  start: # 8
  end: # 22

# 自动生成按钮
auto_open_sidebar:
  enable: true

# 网站验证
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:

# Bing Webmaster tools verification setting
# See: https://www.bing.com/toolbox/webmaster/
bing_site_verification:

# Yandex Webmaster tools verification setting
# See: https://webmaster.yandex.ru/
yandex_site_verification:

# Baidu Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification:

# 360 Webmaster tools verification setting
# see http://zhanzhang.so.com/
qihu_site_verification:

# 分析统计
# Google Analytics
# https://developers.google.com/analytics/devguides/collection/analyticsjs/
google_analytics:

# Baidu Analytics
# https://tongji.baidu.com/web/welcome/login
baidu_analytics:

# Tencent Analytics
# https://mta.qq.com
tencent_analytics:

# CNZZ Analytics
# https://www.umeng.com/
cnzz_analytics:

# Cloudflare Analytics
# https://www.cloudflare.com/web-analytics/
cloudflare_analytics:

# Microsoft Clarity
# https://clarity.microsoft.com/
microsoft_clarity:

# PWA 渐进式Web应用
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: true
  manifest: /manifest.json
  apple_touch_icon: /img/icon-152x152.png
  favicon_32_32: /img/icon-32x32.png
  favicon_16_16: /img/icon-16x16.png
  mask_icon: /img/safari-pinned-tab.svg
  theme_color: "#49b1f5"

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta:
  enable: true
  option:
    # twitter_card:
    # twitter_image:
    # twitter_id:
    # twitter_site:
    # google_plus:
    # fb_admins:
    # fb_app_id:

# 添加CSS和JS - 性能优化
inject:
  head:
    - <link rel="stylesheet" href="//at.alicdn.com/t/c/font_3846514_kabxni94auf.css">
    - <link rel="stylesheet" href="/css/custom.css">
    - <link rel="stylesheet" href="/css/performance.css">
    - <link rel="stylesheet" href="/css/mobile-optimization.css">
    - <link rel="stylesheet" href="/css/content-management.css">
    # 已禁用的CSS文件（避免与主题冲突）
    # - <link rel="stylesheet" href="/css/theme-enhancement.css">
    # - <link rel="stylesheet" href="/css/mermaid-style.css">
    - <link rel="stylesheet" href="/css/categories-page.css">
    # 预加载关键资源
    - <link rel="preload" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@latest/css/all.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    - <link rel="preconnect" href="https://cdn.jsdelivr.net">
    - <link rel="dns-prefetch" href="//cdn.jsdelivr.net">
    # 性能优化meta标签
    - <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    - <meta http-equiv="X-UA-Compatible" content="IE=edge">
  bottom:
    - <script src="/js/custom.js"></script>
    - <script src="/js/performance.js"></script>
    - <script src="/js/structured-data.js"></script>
    - <script src="/js/seo-meta.js"></script>
    # 已禁用的JS文件（避免与主题冲突）
    # - <script src="/js/enhanced-search.js"></script>
    - <script src="/js/ux-enhancement.js"></script>
    - <script src="/js/related-posts.js"></script>
    - <script src="/js/tag-category-manager.js"></script>
    # - <script src="/js/theme-enhancement.js"></script>
    # - <script src="/js/mermaid-init.js"></script>
    - <script src="/js/categories-data.js"></script>
    - <script src="/js/categories-page.js"></script>

# CDN设置 - 性能优化
CDN:
  # The CDN provider of internal scripts (主题内部 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( dev版的主题只能设置为 local )
  internal_provider: jsdelivr

  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # when set it to local, you need to install hexo-butterfly-extjs
  third_party_provider: jsdelivr

  # Add version number to CDN, true or false
  version: true

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
    # 主要库使用CDN加速
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    jquery_ui: https://cdn.jsdelivr.net/npm/jquery-ui@latest/dist/jquery-ui.min.js
    fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@latest/css/all.min.css
    # prismjs CDN已禁用，避免与highlight.js冲突
    # prismjs_css: https://cdn.jsdelivr.net/npm/prismjs@latest/themes/prism.min.css
    # prismjs_js: https://cdn.jsdelivr.net/npm/prismjs@latest/components/prism-core.min.js

# 文章版权信息
post_copyright:
  enable: true
  decode: false
  author_href: https://uwakeme.top/about/
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 文章过期提醒
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 1000
  position: top # position: top/bottom
  message_prev: 本文最后更新于
  message_next: 天前，文中内容可能已过时，请谨慎参考。

# 相关文章推荐
related_post:
  enable: false  # 禁用主题自带的相关推荐，使用自定义推荐系统
  limit: 6 # 显示推荐文章数目
  date_type: created # or created or updated 文章日期显示创建日或者更新日

# 打赏 Sponsor/reward
reward:
  enable: true  # 是否启用打赏功能
  QR_code:
     - img: /img/wechat.jpg
       link:
       text: 微信
     - img: /img/alipay.jpg
       link:
       text: 支付宝

# 分享功能 AddToAny
# https://www.addtoany.com/
addtoany:
  enable: false
  item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link

# toc (目录)
toc:
  post: true
  page: false
  number: false
  expand: true # 是否展开
  style_simple: false # for post
  scroll_percent: true


# Background effects (背景特效)
# canvas_ribbon (静止彩带)
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false
# Fluttering Ribbon (动态彩带)
canvas_fluttering_ribbon:
  enable: true
  mobile: true
#星空特效
# canvas_nest
# https://github.com/hustcc/canvas-nest.js
canvas_nest:
  enable: true
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false

# wordcount (字数统计)
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# ==================================== 高级功能配置 ====================================

# 鼠标点击效果
fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# 文字点击效果
ClickShowText:
  enable: false
  text:
    - 富强
    - 民主
    - 文明
    - 和谐
    - 自由
    - 平等
    - 公正
    - 法治
    - 爱国
    - 敬业
    - 诚信
    - 友善
  fontSize: 15px
  random: true
  mobile: false

# 网站运行时间
runtimeshow:
  enable: true
  publish_date: 2024/08/29 00:00:00  # 网站上线时间
  format: '本站已运行 {d} 天 {h} 小时 {m} 分钟 {s} 秒'

# 访客统计 (busuanzi)
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 美化配置
beautify:
  enable: true
  field: post # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: '#F47466'

# 页面加载动画
preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  source: 1
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url: https://cdn.jsdelivr.net/npm/pace-js@1.2.4/themes/blue/pace-theme-minimal.css

# 评论功能
comments:
  # Up to two comments system, the first will be shown as default
  # Leave it empty if you don't need comments
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo/Giscus/Remark42/Artalk
  # Format of two comments system : Disqus,Waline
  use: Disqusjs
  # Display the comment name next to the button
  text: true
  # Lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  # Display comment count in post's top_img
  count: true
  # Display comment count in Home Page
  card_post_count: true

disqusjs:
  shortname: uwakeme
  apikey: B8nMqe9biE6yezafjREQRGw9Cx00rv0nCHIuYvHSZy3QDwdFmD058KDxQf5yIbKC
  option:

# Mermaid
# https://github.com/mermaid-js/mermaid
mermaid:
  enable: true
  # Write Mermaid diagrams using code blocks
  code_write: true
  # built-in themes: default / forest / dark / neutral
  theme:
    light: default
    dark: dark
  # CDN
  cdn: https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js

syntax_highlighter: 'highlight.js'
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
  exclude_languages: []
# prismjs配置已禁用，避免与highlight.js冲突
# prismjs:
#   preprocess: true
#   line_number: true
#   tab_replace: ''
#   exclude_languages: []

# https://instant.page/
# prefetch (預加載)
instantpage: true

